export const GET_TRENDING = "GET_TRENDING";
export const GET_MOVIE_DATA = "GET_MOVIE_DATA";
export const FETCH_SIMILAR_MOVIE = "FETCH_SIMILAR_MOVIE";
export const GET_DETAILS = "GET_DETAILS";
export const GET_TVSHOW_DATA = "GET_TVSHOW_DATA";
export const GET_TV_SHOW_DETAILS = "GET_TV_SHOW_DETAILS";
export const GET_TV_SHOW_TRAILER = "GET_TV_SHOW_TRAILER";
export const SET_LOADING = "SET_LOADING";
export const GET_NEXT_PAGE = "GET_NEXT_PAGE";
export const GET_PREV_PAGE = "GET_PREV_PAGE";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const SET_ERROR = "GET_ERROR";
export const CLEAR_STATE = "CLEAR_STATE";
export const REGISTER_USER = "REGISTER_USER";
