//Fetch Data types
export const GET_TRENDING = "GET_TRENDING";
export const GET_MOVIE_DATA = "GET_MOVIE_DATA";
export const FETCH_SIMILAR_MOVIE = "FETCH_SIMILAR_MOVIE";
export const GET_DETAILS = "GET_DETAILS";
export const GET_TVSHOW_DATA = "GET_TVSHOW_DATA";
export const GET_TV_SHOW_DETAILS = "GET_TV_SHOW_DETAILS";
export const GET_TV_SHOW_TRAILER = "GET_TV_SHOW_TRAILER";
export const SET_LOADING = "SET_LOADING";
export const SET_ERROR = "SET_ERROR";
export const CLEAR_STATE = "CLEAR_STATE";
export const GET_NEXT_PAGE = "GET_NEXT_PAGE";
export const GET_PREV_PAGE = "GET_PREV_PAGE";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const GET_MOVIE_NEXT_PAGE = "GET_MOVIE_NEXT_PAGE";
export const GET_MOVIE_PREV_PAGE = "GET_MOVIE_PREV_PAGE";
export const GET_TV_NEXT_PAGE = "GET_TV_NEXT_PAGE";
export const GET_TV_PREV_PAGE = "GET_TV_PREV_PAGE";
export const GET_EPISODE_DETAILS = "GET_EPISODE_DETAILS";

// Persisiting tracked flicks types
export const GET_TRACKED_FLICK_LIST = "GET_TRACKED_FLICK_LIST";
export const FLICK_LIST_FETCH_FAILED = "FLICK_LIST_FETCH_FAILED=";
export const TRACK_FLICK = "TRACK_FLICK";
export const FLICK_ERROR = "FLICK_ERROR";

//Auth types
export const AUTH_LOADING = "AUTH_LOADING";
export const RESET_SUCESS = "RESET_SUCESS";
export const RESET_FAILED = "RESET_FAILED";
export const RESET_PASS_SUCESS = "RESET_PASS_SUCESS";
export const RESET_PASS_FAILED = "RESET_PASS_FAILED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOG_OUT = "LOG_OUT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const REGISTER_USER = "REGISTER_USER";

//Other Actions
export const CLEAR_FLICK_STATE = "CLEAR_FLICK_STATE";
export const FLICK_FETCH_LOADING = "FLICK_FETCH_LOADING";
export const SET_SEARCH_LOADING = "SET_SEARCH_LOADING";
export const SEARCH_SUCESS = "SEARCH_SUCESS";
export const SEARCH_FAILED = "SEARCH_FAILED";
